backend/modules/cars/models/BrandCars.php
<?php

namespace backend\modules\cars\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "brand_cars".
 *
 * @property int $id
 * @property string $name
 */
class BrandCars extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'brand_cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    public static function getList()
    {
        $list = self::find()->asArray()->all(); 
        return ArrayHelper::map($list, 'id', 'name'); 
    }

}

backend/modules/cars/models/ColorCars.php
<?php

namespace backend\modules\cars\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "color_cars".
 *
 * @property int $id
 * @property string $color
 */
class ColorCars extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'color_cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['color'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'color' => 'Color',
        ];
    }

    public static function getList()
    {
        $list = self::find()->asArray()->all();
        return ArrayHelper::map($list, 'id', 'color');
    }

}

backend/modules/cars/controllers/CarsController.php
<?php

namespace backend\modules\cars\controllers;

use Yii;
use backend\models\Cars;
use backend\models\User;
//use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\modules\cars\models\BrandCars;
use backend\modules\cars\models\ColorCars;

/**
 * CarsController implements the CRUD actions for Cars model.
 */
class CarsController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['admin'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'delete', 'update'],
                        'roles' => ['admin'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Cars models.
     * @return mixed
     */
    public function actionIndex()
    {
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
        $carList = Cars::find()->all();
        $usersList = User::getlist();
        return $this->render('index', [
                    'carList' => $carList,
                    'colors' => $colors,
                    'brands' => $brands,
                    'usersList' => $usersList,
        ]);
    }

    /**
     * Displays a single Cars model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cars model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cars();
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
        $usersList = User::getlist();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Автомобиль добавлен!');
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect('index');
        }

        return $this->render('create', [
                    'model' => $model,
                    'colors' => $colors,
                    'brands' => $brands,
                    'usersList' => $usersList,
        ]);
    }

    /**
     * Updates an existing Cars model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
        $usersList = User::getlist();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Данные обновлены!');
            return $this->redirect('index');
        }
        return $this->render('update', [
                    'model' => $model,
                    'colors' => $colors,
                    'brands' => $brands,
                    'usersList' => $usersList,
        ]);
    }

    /**
     * Deletes an existing Cars model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('info', 'Автомобиль удален!');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Cars model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cars the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cars::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

backend/modules/cars/controllers/DefaultController.php
<?php

namespace backend\modules\cars\controllers;

use yii\web\Controller;

/**
 * Default controller for the `cars` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

backend/modules/cars/views/cars/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Cars */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cars-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_user')->dropDownList($usersList) ?>

    <?= $form->field($model, 'id_color')->dropDownList($colors) ?>

    <?= $form->field($model, 'id_brand')->dropDownList($brands) ?>

    <?= $form->field($model, 'number_car')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/cars/views/cars/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Cars */

$this->title = 'Добавить автомобиль';
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cars-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'colors' => $colors,
        'brands' => $brands,
        'usersList' => $usersList,
    ])
    ?>

</div>

backend/modules/cars/views/cars/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Admin Cars';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cars-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Car', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <table class="table table-condensed">
        <tr>
            <th>ID</th>
            <th>User name</th>
            <th>Цвет</th>
            <th>Марка</th>
            <th>Гос. номер</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php foreach ($carList as $car): ?>
        <tr>
            <td> <?php echo $car->id; ?></td>
            <td> <?php echo $usersList[$car->id_user];?></td>
            <td> <?php echo $colors[$car->id_color]; ?></td>
            <td> <?php echo $brands[$car->id_brand]; ?></td>
            <td> <?php echo $car->number_car; ?></td>
            <td><a href="<?php echo Url::to(['cars/update', 'id' => $car->id]); ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
            <td><a href="<?php echo Url::to(['cars/delete', 'id' => $car->id]); ?>" data-confirm="Вы уверены, что хотите удалить автомобиль?" data-method="post"><span class="glyphicon glyphicon-trash"></span></a></td>
            <td></td>

        </tr>

        <?php endforeach; ?>
    </table>
</div>

backend/modules/cars/views/cars/update.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Cars */

$this->title = 'Update Cars: ' . $model->number_car;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cars-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'colors' => $colors,
        'brands' => $brands,
        'usersList' => $usersList,
    ])
    ?>

</div>

backend/modules/cars/views/cars/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Cars */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cars-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_user',
            'id_color',
            'id_brand',
            'number_car',
        ],
    ]) ?>

</div>

backend/modules/cars/views/default/index.php
<div class="cars-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>