backend/models/Cars.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "user_cars".
 *
 * @property int $id
 * @property int $id_user
 * @property int $id_color
 * @property int $id_brand
 * @property string $number_car
 */
class Cars extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'number_car'], 'required'],
            [['id_user', 'id_color', 'id_brand'], 'integer'],
            [['number_car'], 'string', 'max' => 255],
            [['number_car'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_color' => 'Id Color',
            'id_brand' => 'Id Brand',
            'number_car' => 'Number Car',
        ];
    }
}

frontend/models/Car.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "user_cars".
 *
 * @property int $id
 * @property int $id_user
 * @property int $id_color
 * @property int $id_brand
 * @property string $number_car
 */
class Car extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'user_cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['id_user', 'number_car'], 'required'],
            [['id_user', 'id_color', 'id_brand'], 'integer'],
            [['number_car'], 'string', 'max' => 255],
            [['number_car'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_color' => 'Цвет',
            'id_brand' => 'Марка',
            'number_car' => 'Гос. номер',
        ];
    }
    
    /**
     * Получаем данные о автомобилях юзера по id user
     * 
     * @param type $idUser
     * @return array
     */
    public static function getCarData($idUser) {
        $CarData = Car::find()
                ->where(['id_user' => $idUser])
                ->one();

        return $CarData;
    }

}

frontend/controllers/CarController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Car;
//use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\ColorCars;
use frontend\models\BrandCars;
use frontend\controllers\behaviors\AccessBehavior;

/**
 * CarController implements the CRUD actions for Car model.
 */
class CarController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            AccessBehavior::className(),
        ];
    }

    /**
     * Lists all Car models.
     * @return mixed
     */
    public function actionIndex() {
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
//        $carList = Car::find()->all();
        $carList = Car::find()
                ->where(['id_user' => Yii::$app->user->id])
                ->all();
        return $this->render('index', [
                    'carList' => $carList,
                    'colors' => $colors,
                    'brands' => $brands,
        ]);
    }

    /**
     * Displays a single Car model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();

        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'colors' => $colors,
                    'brands' => $brands,
        ]);
    }

    /**
     * Creates a new Car model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Car();
        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
        
        $model->id_user = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->number_car]);
            Yii::$app->session->setFlash('success', 'Автомобиль добавлен!');
            return $this->redirect(['car/index']);
        }

        return $this->render('create', [
                    'model' => $model,
                    'colors' => $colors,
                    'brands' => $brands,
        ]);
    }

    /**
     * Updates an existing Car model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $colors = ColorCars::getlist();
        $brands = BrandCars::getlist();
        $model->id_user = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Автомобиль обновлен!');
            return $this->redirect('index');
        }

        return $this->render('update', [
                    'model' => $model,
                    'colors' => $colors,
                    'brands' => $brands,
        ]);
    }

    /**
     * Deletes an existing Car model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = Car::findOne($id);
        $model->delete();
        Yii::$app->session->setFlash('success', 'Автомобиль удален!');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Car model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Car the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Car::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionGuest()
    {
        return $this->render('/car/guest');
    }

}

frontend/views/car/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Car */
/* @var $form yii\widgets\ActiveForm */
/* @var $colors array */
/* @var $brands array */
?>

<div class="car-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_color')->dropDownList($colors) ?>

    <?= $form->field($model, 'id_brand')->dropDownList($brands) ?>

    <?= $form->field($model, 'number_car')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/car/_updateform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Car */
/* @var $form yii\widgets\ActiveForm */
/* @var $colors array */
/* @var $brands array */
?>

<div class="car-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_color')->dropDownList($colors) ?>

    <?= $form->field($model, 'id_brand')->dropDownList($brands) ?>

    <?= $form->field($model, 'number_car')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/car/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Car */
/* @var $colors array */

$this->title = 'Create Car';
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'colors' => $colors,
        'brands' => $brands,
    ]) ?>

</div>

frontend/views/car/guest.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<h2>Сервис доступен только для зарегестрированых пользователей</h2>
<br><br>

 <?= Html::a('Зарегистрируйтесль', ['/site/signup'], ['class' => 'btn btn-primary center-block']) ?>
<br>  <br>
 <?= Html::a('Залогинтесь', ['/site/login'], ['class' => 'btn btn-success center-block']) ?>

frontend/views/car/index.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cars';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Car', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <table class="table table-condensed">
        <tr>
            <th>Цвет</th>
            <th>Марка</th>
            <th>Гос. номер</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php foreach ($carList as $car): ?>
        <tr>
            <td> <?php echo $colors[$car->id_color]; ?></td>
            <td> <?php echo $brands[$car->id_brand]; ?></td>
            <td> <?php echo $car->number_car; ?></td>
            <td><a href="<?php echo Url::to(['car/update', 'id' => $car->id]); ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
            <td><a href="<?php echo Url::to(['car/delete', 'id' => $car->id]); ?>" data-confirm="Вы уверены, что хотите удалить автомобиль?" data-method="post"><span class="glyphicon glyphicon-trash"></span></a></td>
            <td></td>

        </tr>

        <?php endforeach; ?>
    </table>
</div>

frontend/views/car/update.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Car */

$this->title = 'Update Car: ' . $model->number_car;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->number_car, 'url' => ['view', 'id' => $model->number_car]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="car-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_updateform', [
        'model' => $model,
        'colors' => $colors,
        'brands' => $brands,
    ]) ?>

</div>

frontend/views/car/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Car */

$this->title = $model->number_car;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_user], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_user], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= $model->id_user ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_user',
            'id_color',
            'id_brand',
            'number_car',
        ],
    ]) ?>

</div>